### ISSUE TITLE
Heating Controls?

### ISSUE THREAD

**Issue by Tuckie** [mikegoubeaux/UndermountAC#1]
Curious if/how this would integrate with the heat extension module?: https://undermountac.com/products/heat-addition-module-complete-with-espar-canbus-module

**Comment by mikegoubeaux** [comment]
@Tuckie the link you provided includes the UAC thermostat—which is not their ESPHome thermostat. My config is for their [ESPHome thermostat](https://undermountac.com/collections/thermostats/products/esphome-thermostat-controller-12-30v-dc). But there are extra outputs on the ESPHome thermostat you could add configuration to control a valve or call for heat.

**Comment by Tuckie** [comment]
Mainly I was hoping there was a way to go from the RS485 port on the the ESPHome thermostat to the (assumed) RS485 communication of the heat control unit to act as a expander/bridge for the Espar heater's Canbus.

**Comment by mikegoubeaux** [comment]
@Tuckie You'd need to know the protocol UAC is using on the RS485 and then you could feasibly add configuration to ESPHome on their ESPHome Thermostat to confer with the heat control unit.

**Comment by Tuckie** [comment]
The good news is it appears to be a standard modbus relay controller:

![Image](https://github.com/user-attachments/assets/3a0d85a9-cfac-4039-b9f3-cd27ad4fbf1e)

https://huayng.com/products/csio-404

https://onefexindustrial.com/wp-content/uploads/2022/05/CS-IO404-Manual-V1.2.0.pdf

The bad news is, unfortunately I purchased the standard thermostat as I didn't think it would be this easy to wire up and control the two sides of this heating and cooling coin.

**Comment by wildes1** [comment]
I just got this running today, the fork is [https://github.com/wildes1/UndermountAC](https://github.com/wildes1/UndermountAC).  It's very specific to my use case but may be helpful.  More doc on the modbus relay controller: [https://www.mouser.com/pdfDocs/Product-Overview-DFRobot-FIT0827.pdf](https://www.mouser.com/pdfDocs/Product-Overview-DFRobot-FIT0827.pdf).  

Note I used just the Modbus relays, I don't have the Canbus controller, though I may upgrade to it as it's supposed to have "priming" capability that my present Espar controller doesn't seem to have.

**Comment by Tuckie** [comment]
Very cool! It may take a bit for me to digest all the changes you made, but it would be great to look at merging at least some of your hard work. I may need to see if UMAC would be willing to swap out the (Yet to be installed) MQTT thermostat for the ESP version.

**Comment by wildes1** [comment]
FYI, I fixed a bug that used the heating setpoint to determine fan speed when cooling was called.  Fork has been updated: [https://github.com/wildes1/UndermountAC](https://github.com/wildes1/UndermountAC)
